#!/bin/sh

# ci_post_clone.sh — Xcode Cloud runs this immediately after cloning the repo,
# before it resolves dependencies or invokes xcodebuild.
#
# AnimalSpin.xcodeproj and Support/Info.plist are generated by XcodeGen from
# project.yml and are intentionally git-ignored (see .gitignore), so a fresh
# clone has no project to build — Xcode Cloud fails with:
#   "Project AnimalSpin.xcodeproj does not exist at the root of the repository"
# Install XcodeGen and regenerate the project (and its shared AnimalSpin scheme)
# here so xcodebuild finds it.

set -e

# Homebrew lives at /opt/homebrew on Xcode Cloud's Apple-silicon runners.
export PATH="/opt/homebrew/bin:$PATH"
export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_NO_INSTALL_CLEANUP=1

echo "▸ Installing XcodeGen…"
brew install xcodegen

# Xcode Cloud invokes ci_scripts from the ci_scripts/ directory; generate at the
# repository root instead.
cd "$CI_PRIMARY_REPOSITORY_PATH"

echo "▸ Generating AnimalSpin.xcodeproj from project.yml…"
xcodegen generate

echo "▸ Done — generated:"
ls -d AnimalSpin.xcodeproj Support/Info.plist
