// Generated by AnimalSpin-Resources tools/gen_ios.py from animals.json. Do not edit by hand.
//
// The animals shown in the grid, in display order (the manifest's `status == "active"` set).
// Each case's rawValue is its image-asset name and the stem of its localization key. To change
// the roster, edit animals.json in the resources submodule and re-run the generator.

import Foundation

enum Animal: String, CaseIterable, Identifiable {
    case bear, cat, chicken, cicada, cow, cricket, crow, dog, donkey, duck
    case frog, goat, goose, horse, hyena, lion, monkey, owl, parrot, peacock
    case pig, sheep, squirrel, tiger

    var id: String { rawValue }

    /// Image-asset name (Assets.xcassets), e.g. `cat`.
    var imageName: String { rawValue }

    /// Localization key for the spoken intro ("a cat says"), e.g. `tts_cat_says`.
    var ttsKey: String { "tts_\(rawValue)_says" }

    /// Human-readable name for accessibility (VoiceOver), e.g. `Cat`.
    var displayName: String { rawValue.capitalized }

    /// Recorded clip resource names (mp3, without extension) for this animal.
    var soundClips: [String] { AnimalSounds.clips[self] ?? [] }
}
