// Generated by tools/gen_assets.py from the Android AnimalSpin source. Do not edit by hand.
// Maps each Animal to its recorded clip resource names (mp3 in the app bundle).

enum AnimalSounds {
    /// Clip resource names (without extension) for each animal, in source order.
    static let clips: [Animal: [String]] = [
        .bear: ["bear_fs1", "bear_fs2", "bear_fs3", "bear_fs4", "bear_fs5"],
        .cat: ["cat_bsb1", "cat_bsb2", "cat_bsb3", "cat_bsb4", "cat_fs1", "cat_fs2", "cat_fs3", "cat_fs4", "cat_fs5", "cat_fs6"],
        .chicken: ["chicken_bsb1", "chicken_bsb2", "chicken_bsb3", "chicken_bsb4", "chicken_bsb5", "chicken_fs1", "chicken_fs3", "chicken_fs5"],
        .cicada: ["cicada_fs1", "cicada_fs2", "cicada_fs3", "cicada_fs4", "cicada_fs5", "cicada_fs6", "cicada_fs7", "cicada_fs8", "cicada_fs9", "cicada_fs10"],
        .cow: ["cow_bsb1", "cow_fs1", "cow_fs2", "cow_fs3", "cow_fs4", "cow_fs5", "cow_fs7", "cow_fs8", "cow_fs9"],
        .cricket: ["cricket_fs1", "cricket_fs2", "cricket_fs3", "cricket_fs4", "cricket_fs5"],
        .crow: ["crow_fs1", "crow_fs2", "crow_fs3", "crow_fs4", "crow_fs5"],
        .dog: ["dog_bsb1", "dog_bsb2", "dog_bsb3", "dog_fs1", "dog_fs2", "dog_fs3", "dog_fs4", "dog_fs5", "dog_fs6", "dog_fs7"],
        .donkey: ["donkey_bsb1", "donkey_fs1", "donkey_fs2", "donkey_fs3", "donkey_fs4", "donkey_fs6", "donkey_fs7", "donkey_fs8", "donkey_fs9"],
        .duck: ["duck_bsb1", "duck_fs1", "duck_fs2", "duck_fs3", "duck_fs4", "duck_fs5", "duck_fs6", "duck_fs7", "duck_fs8", "duck_fs9"],
        .frog: ["frog_fs1", "frog_fs2", "frog_fs3", "frog_fs4", "frog_fs5", "frog_fs7", "frog_fs8", "frog_fs9"],
        .goat: ["goat_bsb1", "goat_bsb2", "goat_bsb3", "goat_fs1", "goat_fs2", "goat_fs3", "goat_fs4", "goat_fs5", "goat_fs6", "goat_fs7"],
        .goose: ["goose_fs1", "goose_fs2", "goose_fs3", "goose_fs4", "goose_fs5"],
        .horse: ["horse_bsb1", "horse_fs1", "horse_fs2", "horse_fs3", "horse_fs4", "horse_fs5", "horse_fs6", "horse_fs7", "horse_fs8", "horse_fs9"],
        .hyena: ["hyena_fs1", "hyena_fs2", "hyena_fs3", "hyena_fs4", "hyena_fs5"],
        .lion: ["lion_fs1", "lion_fs2", "lion_fs6", "lion_fs7", "lion_fs10"],
        .monkey: ["monkey_fs1", "monkey_fs2", "monkey_fs3", "monkey_fs5", "monkey_fs6", "monkey_fs9", "monkey_fs10"],
        .owl: ["owl_bsb1", "owl_fs1", "owl_fs3", "owl_fs4", "owl_fs5", "owl_fs7", "owl_fs9"],
        .parrot: ["parrot_fs1", "parrot_fs2", "parrot_fs3", "parrot_fs4", "parrot_fs5"],
        .peacock: ["peacock_fs1", "peacock_fs2", "peacock_fs3", "peacock_fs4", "peacock_fs5", "peacock_fs6", "peacock_fs7", "peacock_fs8", "peacock_fs10"],
        .pig: ["pig_fs1", "pig_fs2", "pig_fs3", "pig_fs4", "pig_fs5"],
        .sheep: ["sheep_fs1", "sheep_fs2", "sheep_fs3", "sheep_fs4", "sheep_fs5", "sheep_fs7", "sheep_fs8"],
        .squirrel: ["squirrel_fs1", "squirrel_fs4", "squirrel_fs5"],
        .tiger: ["tiger_fs1", "tiger_fs2", "tiger_fs3", "tiger_fs4", "tiger_fs5"],
    ]
}
